---
title: "Getting Started with R"
author: '@Haruo_Suzuki'
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    theme: united
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

https://www.yodosha.co.jp/yodobook/book/9784758120951/
Rをはじめよう生命科学のためのRStudio入門 - 羊土社

# 第1章 Rと仲よくなろう

## 1.1.はじめてみる
## 1.2.まずは R をインストールする

https://doi.org/10.7875/togotv.2018.098
2018-04-08 統計解析ソフト「R」の使い方 〜Rの導入・パッケージの導入・作図・統計解析の基本編〜

## 1.3.RStudio をインストールする

https://doi.org/10.7875/togotv.2017.043
2017-05-12 RStudioでRを直感的に使おう MacOS版 2017

## 1.4.どこからはじめるか

p.26
```{r}
1+1
```

## 1.5.とりあえずデカい電卓として使ってみよう
p.27

```{r}
2 * 4
3/8
11.75 - 4.813
10^2
log(10)
log10(10)
sin(2 * pi)
7 < 10
```

### 1.5.1
```{r}
1:10
```

### 1.5.2
```{r}
seq(from = 1, to = 10, by = 1)
seq(from = 1, to = 10, by = 0.5)
x <- seq(from = 1, to = 10, by = 0.5)
x
y <- seq(from = 101, to = 110, by = 0.5)
x + y
```

p.33
## 1.6.スクリプトを書いてみる
### 1.6.1
```{r}
# Clear R's brain
rm(list = ls())
```

## 1.7.総まとめ(ここまでの)

## 1.8.大事なのはパッケージ
```{r}
#install.packages("tidyverse")
```
### 1.8.1
p.41
```{r}
# make these packages and their associated functions
# available to use in this script
library(dplyr)
library(ggplot2)
#library(tidyverse)
```

## 1.9.いつでもヘルプ
```{r}
?read.csv
```

## 1.10.本格的な例(ちょっとだけ)

## 1.11.最初のうち(そして今後も)うまくやっていくコツ

## 付録1a.課題の解答例
p.49
```{r}
rm(list = ls())
library(ggplot2)

# Exercise 1
# Plot a grah with x^2 on the y-axis and x on the x-axis.
x <- seq(-10, 10, 0.1)
y <- x^2
qplot(x, y, geom="line")

# Exercise 2
# Plot a grah with sine on the y-axis and x on the x-axis.
x <- seq(0, 8*pi, 0.1)
y <- sin(x)
qplot(x, y, geom="line")

# Exercise 3
# Plot a histogram of 1000 random normal deviates.
x <- rnorm(1000)
qplot(x)
```

## 付録1b.ファイルの拡張子と OS による違い

# R environment
```{r}
# Collect Information About the Current R Session
sessionInfo()
```

# References
- https://github.com/haruosuz/books/tree/master/r4all
